# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'bootJar'
  - script: |
      mv ./kotlin-rest-example.jar ./app.jar
    displayName: Prepare Gradle Spring Boot Jar for MS Maven Deploy
    name: gradle_Spring_Boot_Transform_To_Maven_Jar
    workingDirectory: '$(Build.SourcesDirectory)/build/libs'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/libs'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Visual Studio Enterprise Subscription (fc099a2b-6d5f-40bb-a8da-c87f37d942f9)'
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az webapp deployment source config-zip -g american-airlines-demo -n kotlin-example-zip --src $(System.DefaultWorkingDirectory)/$(Build.BuildId).zip

#      jar xvf ./kotlin-rest-example.jar
#      rm -r META-INF
#      rm -r org
#      jar cvfm0 kotlin-rest-example.jar ./META-INF/MANIFEST.MF
#      jar tvf kotlin-rest-example.jar
#      jar i ./kotlin-rest-example.jar
