# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'bootJar'
  - script: |
      jar xvf ./kotlin-rest-example.jar
    workingDirectory: '$(Build.SourcesDirectory)/build/libs'
#  - task: AzureRmWebAppDeployment@4
#    inputs:
#      ConnectionType: 'AzureRM'
#      azureSubscription: 'azdo-service-connection'
#      appType: 'webAppLinux'
#      WebAppName: 'kotlin-rest-example'
#      deployToSlotOrASE: false
#      packageForLinux: '$(System.DefaultWorkingDirectory)/build/libs/*.jar'
#      RuntimeStack: 'JAVA|8-jre8'
#  - task: PublishPipelineArtifact@1
#    inputs:
#      targetPath: '$(Build.SourcesDirectory)/build/libs'
#      artifactName: 'kotlin-rest-api'
